//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaskiPlacowe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaskiPlacowe
    {
        public long ID_PASKA { get; set; }
        public string NAZWA { get; set; }
        public long ID_UZYTKOWNIKA { get; set; }
        public byte[] PLIK { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
