//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaskiPlacowe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaskiPlacowe_POZ
    {
        public long ID_PASEK_PLACOWY_POZ { get; set; }
        public long ID_TYPU_POLA { get; set; }
        public long ID_PASKA { get; set; }
        public string WARTOSC { get; set; }
    
        public virtual PaskiPlacowe PaskiPlacowe { get; set; }
        public virtual SL_TYPOW_POL_PP SL_TYPOW_POL_PP { get; set; }
    }
}
