//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaskiPlacowe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_GRUPY_TYPOW_POL_PP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SL_GRUPY_TYPOW_POL_PP()
        {
            this.SL_TYPOW_POL_PP = new HashSet<SL_TYPOW_POL_PP>();
        }
    
        public long ID_GRUPY { get; set; }
        public string Nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SL_TYPOW_POL_PP> SL_TYPOW_POL_PP { get; set; }
    }
}
