//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaskiPlacowe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_TYPOW_POL_PP
    {
        public long ID_TYPU_POLA { get; set; }
        public string KOD { get; set; }
        public string NAZWA { get; set; }
        public bool UNIKALNY { get; set; }
    }
}
