//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaskiPlacowe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaskiPlacowe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA foreign_keys=OFF;
        ///BEGIN TRANSACTION;
        ///CREATE TABLE [PaskiPlacowe] (        ///
        ///    [ID_PASKA] integer PRIMARY KEY AUTOINCREMENT NOT NULL,        ///
        ///    [NAZWA] varchar(50) NOT NULL,        ///
        ///    [ID_UZYTKOWNIKA] integer NOT NULL,        ///
        ///    [PLIK] blob,        ///
        ///    CONSTRAINT [FK_PaskiPlacowe_-1_-1] FOREIGN KEY ([ID_UZYTKOWNIKA]) REFERENCES [Uzytkownicy] ([ID_UZYTKOWNIKA])        ///
        ///);
        ///CREATE TABLE [PaskiPlacowe_POZ] (        ///
        ///    [ID_PASEK_PLACOWY_POZ] integer PRIMARY KEY NOT NULL,        ///
        ///    [ID_TYPU_POLA] integer NOT NULL,        ///
        ///    [ID_PASKA] integer  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalarySlip {
            get {
                return ResourceManager.GetString("SalarySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin;
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Dane podstawowe&apos;);
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Godziny&apos;);
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Dni&apos;);
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Wynag. OFP&apos;);
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Potrącenia&apos;);
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Podstawy podatkowe&apos;);
        ///insert into SL_GRUPY_TYPOW_POL_PP(NAZWA) VALUES (&apos;Składki&apos;);
        ///
        ///insert into SL_TYPOW_POL_PP(KOD,NAZWA,UNIKALNY, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalarySlip_BASE_INSERTS {
            get {
                return ResourceManager.GetString("SalarySlip_BASE_INSERTS", resourceCulture);
            }
        }
    }
}
